image: ubuntu:groovy
before_script:
    - apt update -qq
    - apt install -qqy --no-upgrade openjdk-15-jdk ant junit
    - export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
build:
    stage: build
    script:
        - ant -S compile
        - ant -S compile-test
    dependencies: []
    artifacts:
        paths:
            - out
        expire_in: 1 hour
test:
    stage: test
    script:
        - ant -S test -Dnorebuild=true
    dependencies:
        - build
    artifacts:
        paths:
            - report
        expire_in: 1 week
production:
    stage: production
    script:
        - ant -S doc
        - ant -S dist -Dnorebuild=true
    dependencies:
        - build
    artifacts:
        paths:
            - out/artifacts/teamgtlib_jar
            - doc
        expire_in: 3 days